server:
  port: 8080

spring:
  application:
    name: spring-boot-test
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/starfish?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456789
  data:
    redis:
      host: sunkolin.xyz
      port: 6379
      password: Jz2AFn5*Hp8&Sw3!Qe6$Lx9^Ar4@Bt7%Cy1wVk0