server:
  port: 8080

spring:
  application:
    name: spring-boot-test
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/starfish?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456789
  data:
    redis:
      host: 8.141.81.187
      port: 6379
      password: redis_mejHMG